### ISSUE TITLE
Interpreting PSD band from .csv files created by pop_eegstats

### ISSUE THREAD

**Issue by BW010** [arnodelorme/eegstats#1]
Dear developers,

I am currently working with EEGLAB and in particular the plugin eegstats to obtain alpha and beta PSD of my EEG data undergoing different filters (ASR is one of them). I am trying to compare beta PSD based on relevant electrode activity but I am a bit puzzled by the data eegstats is producing. Some of my alpha and beta values are negative, but how is that possible given that PSD should be a absolute value. Is the alpha/beta PSD calculated with respect to some baseline or other activity?

**Comment by arnodelorme** [comment]
The values returned are 10*log10(power) so if power is less than 1, negative values can be returned.
